config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :registers, only: [:index, :create]
  resources :dashboard, only: [:index]

  resources :login, only: [:index, :create, :destroy] do
    collection do 
      delete 'delete', action: :destroy, as: :destroy
    end
  end
end


/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[$*&@#])[0-9a-zA-Z$*&@#]{8,128}$/

/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[$*&@#])[0-9a-zA-Z$*&@#]{8,128}$/

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User
  include ActiveModel::Model

  attr_accessor :name, :email, :password

  validates_presence_of :name, :email, message: I18n.t('errors.is_required')
  validates_length_of :name, in: 5..128, message: I18n.t('errors.user_name_range')
  validates_length_of :password, in: 10..128, message: I18n.t('errors.user_password_range')
  validates :email, format: { with: /\A[a-zA-Z0-9_\W]{0,63}@[a-zA-Z0-9.-]*${0,128}\z/,
    message: I18n.t('errors.is_not_valid') }
  validate :password_validation

  private

  def password_validation
    rules = {
      I18n.t('errors.user_password_at_leat_two_lowercase')          => /[a-z]/,
      I18n.t('errors.user_password_at_leat_two_uppercase')          => /[A-Z]/,
      I18n.t('errors.user_password_at_leat_two_digits')             => /[0-9]/,
      I18n.t('errors.user_password_at_leat_two_special_characters') => /\W/
    }

    rules.each do |message, regex|      
      errors.add( :password, message ) if password.scan(regex).length < 2
    end
  end
end


app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :is_authenticate, only: [:index]
  require 'rest-client'
  
  def index
    @localization = JSON.parse(RestClient.get("http://ipinfo.io/#{request.remote_ip}/geo", headers={}))
  end

  private
  def is_authenticate
    redirect_to login_index_path if session[:current_user_email].blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :is_authenticate, only: [:index]

  def index  
  end

  private
  def is_authenticate
    if session[:current_user_name] && session[:current_user_email] && session[:current_user_password]
      redirect_to dashboard_index_path
    else
      redirect_to login_index_path
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def create
    
    if session[:users].present? && email_and_password_is_valid?
      redirect_to(dashboard_index_path, { flash: { notice: "Login realizado com sucesso!" } } )
    else
      flash.now.alert = "Email ou senha inválidos!"
      render :index
    end
  end

  def destroy
    session[:current_user_name] = nil
    session[:current_user_email] = nil
    session[:current_user_password] = nil

    redirect_to login_index_path
  end

  private
  def email_and_password_is_valid?
    session[:users].each do |user|
      if user['email'] == params['email'] && user['password'] == params['password']
        insert_user_in_current_session(user)
        return true
      end
    end

    return false
  end

  def insert_user_in_current_session(user)
    session[:current_user_name] = user['name']
    session[:current_user_email] = user['email']
    session[:current_user_password] = user['password']
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def index
  end

  def create
    session[:users] = [] if session[:users].blank?
    
    if !load_user
      render :index 
    else 
      session[:users] <<
        { 
          name: @user.name,
          email: @user.email,
          password: @user.password
        }

      insert_user_in_current_session

      redirect_to(login_index_path, { flash: { notice: "Cadastro realizado com sucesso!" } } )
    end
  end

  private
  def insert_user_in_current_session
    session[:current_user_name] = params[:name]
    session[:current_user_email] = params[:email]
    session[:current_user_password] = params[:password]
  end

  def load_user
    @user = User.new
    @user.name = params['name']
    @user.email = params['email']
    @user.password = params['password']

   
    @user.valid?
    email_is_unique
    @user.errors.blank?
  end

  def email_is_unique
    return true if session[:users].blank?

    session[:users].each do |user|
      if params[:email].present? && user['email'] == params[:email]
        @user.errors.add(:email, 'já se encontra em uso.')
        return
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_localization_table.html.erb
<% if @localization.present? && @localization['city'].present? %>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        IP:
      </div>
      <div class="col-sm">
        <%= @localization['ip'] %> 
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        Cidade:
      </div>
      <div class="col-sm">
        <%= @localization['city'] %> 
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        Estado:
      </div>
      <div class="col-sm">
        <%= @localization['region'] %> 
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        País:
      </div>
      <div class="col-sm">
        <%= @localization['country'] %> 
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        Timezone:
      </div>
      <div class="col-sm">
        <%= @localization['timezone'] %> 
      </div>
    </div>
  </div>
<% else %>
  <p>Não foi possivel encontrar sua localização.</p>
<% end %>

app/views/dashboard/index.html.erb
<%= render 'shared/flash' %>

<div class="card mx-auto mt-5" style="max-width: 20rem;">
  <div class="card-body">
    <h5 class="card-title">Olá, <%= session[:current_user_name] %></h5>
    <p class="card-text">Abaixo estão os seus dados de localização neste momento.</p>
    <%= render 'localization_table' %>
  </div>
  <div class="card-body text-center">
    <p><%= link_to 'Finalizar sessão', destroy_login_index_path, method: :delete, data: { confirm: "Você tem certeza?"} %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoCoffeeBean</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/_form.html.erb
<h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Logar</h3>

<div class="form-outline mb-4">
  <label class="form-label" for="emailAdress">Endereço de email</label>
  <%= text_field_tag :email, params[:email], id: 'emailAdress', class: "form-control form-control-lg", required: true %> 
</div>

<div class="form-outline mb-4">
  <label class="form-label" for="password">Password</label>
  <%= password_field_tag :password, params[:password], id: "password", class: "form-control form-control-lg", required: true %>
</div>

<div class="pt-1 mb-4">
  <button class="btn btn-info btn-lg btn-block" type="submit" id=login_button>Entrar</button>
</div>

app/views/login/index.html.erb
<section class="vh-100">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-5 text-black">
        <%= render 'shared/flash' %>
        
        <div class="px-5 ms-xl-4 mt-4">
          <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
          <span class="h1 fw-bold mb-0">Coffee Bean</span>
        </div>

        <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

          <%= form_tag(login_index_path, method: 'post', style: "width: 23rem;") do %>

            <%= render 'form' %>

            <p>Ainda não tem uma conta? <%= link_to 'Registre-se aqui', registers_path, class: 'link-info' %></p>

          <% end %>
        </div>
      </div>
      <div class="col-sm-7 px-0 d-none d-sm-block">
        <img src="https://www.oswaldocruz.com/site/images/artigos/pesquisa_cafe_coracao.jpg"
          alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
      </div>
    </div>
  </div>
</section>

app/views/registers/_form.html.erb
<h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Cadastro</h3>

<div class="form-outline mb-4">
  <label class="form-label" for="name">Nome completo</label>
  <%= text_field_tag :name, params[:name], id: 'name', class: "form-control form-control-lg"%>
</div>

<div class="form-outline mb-4">
  <label class="form-label" for="email">Email</label>
  <%= text_field_tag :email, params[:email], id: 'email', class: "form-control form-control-lg" %>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle mt-1" viewBox="0 0 16 16"  data-toggle="tooltip" data-placement="top" data-html="true" title="Exemplo: local-part@domain" style="float:right">
    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
  </svg>
</div>

<div class="form-outline mb-4">
  <label class="form-label" for="password">Senha</label>
  <%= password_field_tag :password, params[:password], id: "password", class: "form-control form-control-lg" %>
</div>

<div class="pt-1 mb-4">
  <button class="btn btn-info btn-lg btn-block" type="submit">Cadastre-se</button>
</div>

app/views/registers/index.html.erb
<section class="vh-100">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 text-black">
        <% if @user.present? && @user.errors.any? %>
          <div class="alert alert-danger alert-dismissible">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li> <%= message %> </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="px-5 ms-xl-4 mt-4">
          <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
          <span class="h1 fw-bold mb-0">Coffee Bean</span>
        </div>

        <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

          <%= form_tag(registers_path, method: 'post', style: "width: 23rem;") do %>

            <%= render 'form' %>

            <p>Já tem uma conta? <%= link_to 'Clique aqui e faça seu login', login_index_path, class: 'link-info' %></p>

          <% end %>
        </div>
      </div>
      <div class="col-sm-6 px-0 d-none d-sm-block">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST8mOYbCRw3GFOW37IieZJrdCHkPb5IdtjEQ&usqp=CAU"
          alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
      </div>
    </div>
  </div>
</section>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == "notice" %>
    <div class="alert alert-success">
  <% elsif type == "alert" %>
    <div class="alert alert-danger">
  <% else %>
    <div class='alert alert-<%= "#{type}" %>'>
  <% end %>
      <%= msg %>
      <% msg.clear %>
    </div>
<% end %>